name: Data Refresh

on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
jobs:
  build:
    name: refresh_italy
    runs-on: macOS-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'dplyr', 'lubridate'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Refresh the data
        run: Rscript ./data_raw/github_action.R
      - name: Push updates
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git config --global user.name 'RamiKrispin'
              git config --global user.email 'ramkrisp@umich.edu'
              git commit -am "update italy total"
              git push
          fi
     
