name: Data Refresh

on: [push, pull_request]
  #schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '0 0 * * *'
jobs:
  build:
    name: refresh_italy
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
     
